version: "3.9"
services:
  staking-api-service:
    image: babylonchain/staking-api-service:latest
    container_name: staking-api-service
    ports:
      - "80:8090"
    environment:
      - CONFIG=/home/staking-api-service/config.yml
    volumes:
      - ./config/config-docker.yml:/home/staking-api-service/config.yml:Z
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./bin/init-mongo.sh:/init-mongo.sh
    entrypoint: [ "/init-mongo.sh" ]
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
